url: ''
baseurl: 'marviorocha.com'
title: 'MarvioRocha.Com'

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
