title: Marvio Rocha - Full-stack Developer
email: marviorocha@marviorocha.com
description: Desenvolvimento de software Backend - FullStack Ruby On Rails, Postgres e React
baseurl: ""
url: "https://marviorocha.com"
twitter_username: marviorocha
github_username: marviorocha


plugins:
  - jekyll-feed
  - jekyll-postcss

css_dir: "assets/css"

postcss:
  cache: false
  
exclude:
  - node_modules/
  - yarn.lock
  - postcss.config.js
  - tailwind.config.js
  - package.json
  - README.md
